const Actions = {
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  CURRENT_USER: 'CURRENT_USER',
  API_REQUEST: 'API_REQUEST',
  API_RESPONSE: 'API_RESPONSE'
}

export default Actions
